server {
    listen 80;
    server_name localhost;

    set $MAGE_ROOT /var/www/html;
    set $MAGE_MODE developer;

    include /var/www/html/nginx.conf.sample;

    location ~ ^/static/ {
        # allow requests to static content to bypass rewriting
        root $MAGE_ROOT/pub;
        add_header Cache-Control "public, max-age=31536000";
        add_header X-Content-Type-Options nosniff;
        try_files $uri $uri/ /static.php?resource=$uri;
    }

    location ^~ /media/ {
        root $MAGE_ROOT/pub;
        try_files $uri $uri/ /get.php?$args;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ (\.php$|\.phtml$) {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param MAGE_RUN_TYPE store;
        fastcgi_param MAGE_RUN_CODE default;
    }

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}
